import json
import os
from pathlib import Path
from align import model


test_model = model.Model()

PROJECT_JSON_FILE = "./tests/resources/test_project_settings.json"
PROJECT_TEMP_FILENAME = "./tests/resources/temp_test_project_settings.json"
SETTINGS_DICT = {
    "type": "group",
    "readonly": False,
    "visible": True,
    "enabled": True,
    "renamable": False,
    "removable": False,
    "strictNaming": False,
    "expanded": True,
    "syncExpanded": False,
    "title": None,
    "name": "Parameters",
    "value": None,
    "default": None,
    "children": {
        "metafile": {
            "type": "file",
            "readonly": True,
            "visible": True,
            "enabled": True,
            "renamable": False,
            "removable": False,
            "strictNaming": False,
            "expanded": True,
            "syncExpanded": False,
            "title": "meta file",
            "name": "metafile",
            "nameFilter": "*.meta",
            "value": "tests/resources/test_traces.meta",
            "default": None,
            "directory": "/",
        },
        "number_of_traces": {
            "type": "int",
            "readonly": True,
            "visible": True,
            "enabled": True,
            "renamable": False,
            "removable": False,
            "strictNaming": False,
            "expanded": True,
            "syncExpanded": False,
            "title": "Traces",
            "name": "number_of_traces",
            "value": 70000,
            "default": None,
        },
        "sample_freq": {
            "type": "str",
            "readonly": True,
            "visible": True,
            "enabled": True,
            "renamable": False,
            "removable": False,
            "strictNaming": False,
            "expanded": True,
            "syncExpanded": False,
            "title": "Sample Frequency",
            "name": "sample_freq",
            "value": "2.5GHz",
            "default": None,
        },
        "comment": {
            "type": "text",
            "readonly": True,
            "visible": True,
            "enabled": True,
            "renamable": False,
            "removable": False,
            "strictNaming": False,
            "expanded": True,
            "syncExpanded": False,
            "title": "Comment",
            "name": "comment",
            "value": "TEST COMMENT",
            "default": None,
        },
        "ref_trace": {
            "type": "int",
            "readonly": False,
            "visible": True,
            "enabled": True,
            "renamable": False,
            "removable": False,
            "strictNaming": False,
            "expanded": True,
            "syncExpanded": False,
            "title": "Reference Trace",
            "name": "ref_trace",
            "default": 1,
            "value": 45,
            "limits": [0, 69999],
        },
        "ref_trace_type": {
            "type": "list",
            "readonly": False,
            "visible": True,
            "enabled": True,
            "renamable": False,
            "removable": False,
            "strictNaming": False,
            "expanded": True,
            "syncExpanded": False,
            "title": "EM/Power",
            "name": "ref_trace_type",
            "limits": ["em"],
            "value": "em",
            "default": None,
        },
        "trace_option_group": {
            "type": "group",
            "readonly": False,
            "visible": True,
            "enabled": True,
            "renamable": False,
            "removable": False,
            "strictNaming": False,
            "expanded": True,
            "syncExpanded": False,
            "title": "Traces",
            "name": "trace_option_group",
            "tip": "Click to add traces",
            "addText": "add Trace",
            "value": None,
            "default": None,
            "children": {
                "traceoptions": {
                    "type": "group",
                    "readonly": False,
                    "visible": True,
                    "enabled": True,
                    "renamable": False,
                    "removable": True,
                    "strictNaming": False,
                    "expanded": True,
                    "syncExpanded": False,
                    "title": "Trace 45 options",
                    "name": "traceoptions",
                    "autoIncrementName": True,
                    "context": {"duplicate_trace": "Duplicate"},
                    "value": None,
                    "default": None,
                    "children": {
                        "tracenr": {
                            "type": "int",
                            "readonly": False,
                            "visible": True,
                            "enabled": True,
                            "renamable": False,
                            "removable": False,
                            "strictNaming": False,
                            "expanded": True,
                            "syncExpanded": False,
                            "title": "Trace",
                            "name": "tracenr",
                            "limits": [0, None],
                            "value": 45,
                            "default": 1,
                        },
                        "tracetype": {
                            "type": "list",
                            "readonly": False,
                            "visible": True,
                            "enabled": True,
                            "renamable": False,
                            "removable": False,
                            "strictNaming": False,
                            "expanded": True,
                            "syncExpanded": False,
                            "title": None,
                            "name": "tracetype",
                            "limits": ["em"],
                            "value": "em",
                            "default": None,
                        },
                        "color": {
                            "type": "color",
                            "readonly": False,
                            "visible": True,
                            "enabled": True,
                            "renamable": False,
                            "removable": False,
                            "strictNaming": False,
                            "expanded": True,
                            "syncExpanded": False,
                            "title": "Color",
                            "name": "color",
                            "value": [255, 182, 99, 255],
                            "default": [255, 255, 255, 255],
                        },
                        "shift": {
                            "type": "slider",
                            "readonly": False,
                            "visible": True,
                            "enabled": True,
                            "renamable": False,
                            "removable": False,
                            "strictNaming": False,
                            "expanded": True,
                            "syncExpanded": False,
                            "title": "Shift",
                            "name": "shift",
                            "limits": [-10000, 10000],
                            "value": 0,
                            "default": 0,
                        },
                        "filter_group": {
                            "type": "group",
                            "readonly": False,
                            "visible": True,
                            "enabled": True,
                            "renamable": False,
                            "removable": False,
                            "strictNaming": False,
                            "expanded": True,
                            "syncExpanded": False,
                            "title": "Filter",
                            "name": "filter_group",
                            "addText": "add Filter",
                            "addList": [
                                "gaussian_filter",
                                "moving_average_filter",
                                "abs_filter",
                                "fft_filter",
                                "first_peak_filter",
                                "last_peak_filter",
                                "peak_in_range_filter",
                                "threshold_filter",
                                "variance_filter",
                                "irr_notch_filter",
                                "hanning_filter",
                            ],
                            "context": {
                                "set_batch_filters": "Set filters for batch processing"
                            },
                            "dropEnabled": True,
                            "value": None,
                            "default": None,
                            "children": {
                                "variance_filter": {
                                    "type": "group",
                                    "readonly": False,
                                    "visible": True,
                                    "enabled": True,
                                    "renamable": False,
                                    "removable": True,
                                    "strictNaming": False,
                                    "expanded": True,
                                    "syncExpanded": False,
                                    "title": "Variance Filter",
                                    "name": "variance_filter",
                                    "movable": True,
                                    "value": None,
                                    "default": None,
                                    "children": {
                                        "enabled": {
                                            "type": "bool",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "enabled",
                                            "value": True,
                                            "default": False,
                                        },
                                        "interval_size": {
                                            "type": "int",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "interval_size",
                                            "value": 5000,
                                            "default": None,
                                        },
                                    },
                                },
                                "fft_filter": {
                                    "type": "group",
                                    "readonly": False,
                                    "visible": True,
                                    "enabled": True,
                                    "renamable": False,
                                    "removable": True,
                                    "strictNaming": False,
                                    "expanded": True,
                                    "syncExpanded": False,
                                    "title": "FFT filter",
                                    "name": "fft_filter",
                                    "movable": True,
                                    "value": None,
                                    "default": None,
                                    "children": {
                                        "enabled": {
                                            "type": "bool",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "enabled",
                                            "value": True,
                                            "default": False,
                                        },
                                        "sampleFreq": {
                                            "type": "int",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "sampleFreq",
                                            "value": 20000,
                                            "default": 10000,
                                        },
                                        "frequency": {
                                            "type": "int",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "frequency",
                                            "value": 1,
                                            "default": 1,
                                        },
                                    },
                                },
                                "last_peak_filter": {
                                    "type": "group",
                                    "readonly": False,
                                    "visible": True,
                                    "enabled": True,
                                    "renamable": False,
                                    "removable": True,
                                    "strictNaming": False,
                                    "expanded": True,
                                    "syncExpanded": False,
                                    "title": "Last Peak filter",
                                    "name": "last_peak_filter",
                                    "movable": True,
                                    "value": None,
                                    "default": None,
                                    "children": {
                                        "enabled": {
                                            "type": "bool",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "enabled",
                                            "value": True,
                                            "default": False,
                                        },
                                        "minDist": {
                                            "type": "int",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "minDist",
                                            "default": 10,
                                            "value": 0,
                                        },
                                        "threshold": {
                                            "type": "float",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "threshold",
                                            "value": 121.0,
                                            "default": None,
                                        },
                                        "findMax": {
                                            "type": "bool",
                                            "readonly": False,
                                            "visible": True,
                                            "enabled": True,
                                            "renamable": False,
                                            "removable": False,
                                            "strictNaming": False,
                                            "expanded": True,
                                            "syncExpanded": False,
                                            "title": None,
                                            "name": "findMax",
                                            "value": True,
                                            "default": True,
                                        },
                                    },
                                },
                            },
                        },
                    },
                }
            },
        },
    },
}


## Test the class Model method "save_project_settings" without "use_relative_path" option
#  Ensure that the original metafile path is saved in the settings file.
def test_save_project_settings() -> None:
    test_model.save_project_settings(SETTINGS_DICT, PROJECT_TEMP_FILENAME)
    with open(PROJECT_TEMP_FILENAME, mode="r", encoding="utf-8") as file:
        state = json.loads(file.read())
        assert Path(state["children"]["metafile"]["value"]) == Path(
            "tests/resources/test_traces.meta"
        )
    if os.path.exists(PROJECT_TEMP_FILENAME):
        os.remove(PROJECT_TEMP_FILENAME)


## Test the class Model method "save_project_settings" with "use_relative_path" option set True
#  Ensure that the original metafile path is saved as relative path in the settings file.
def test_save_project_settings_use_relative_path() -> None:
    test_model.save_project_settings(SETTINGS_DICT, PROJECT_TEMP_FILENAME, True)
    with open(PROJECT_TEMP_FILENAME, mode="r", encoding="utf-8") as file:
        state = json.loads(file.read())
        assert Path(state["children"]["metafile"]["value"]) == Path(
            "./test_traces.meta"
        )
    if os.path.exists(PROJECT_TEMP_FILENAME):
        os.remove(PROJECT_TEMP_FILENAME)


## Test the class Model method "load_project_settings"
#  Ensure that the metafile path is read correctly
def test_load_project_settings() -> None:
    settings_dict = test_model.load_project_settings(PROJECT_JSON_FILE)
    assert Path(settings_dict["children"]["metafile"]["value"]) == Path(
        "tests/resources/test_traces.meta"
    )
